services:
  motiond:
    build:
      context: .
      target: debug
    image: motion:debug
    volumes:
      - ./data:/data
      - ./app:/app
    devices:
      - /dev/video0:/dev/video0
    restart: unless-stopped
    ports:
      - "5678:5678"