services:
  motion:
    build:
      context: .
      target: debug
    image: motion:debug
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./app:/app
    devices:
      - /dev/video0:/dev/video0
    restart: unless-stopped
    ports:
      - "5678:5678"
    command:
      - watchmedo
      - auto-restart
      - --directory
      - /app
      - --pattern
      - "*.py"
      - --recursive
      - --
      - python
      - -m
      - debugpy
      - --listen
      - 0.0.0.0:5678
      - --wait-for-client
      - /app/main.py