services:
  motion:
    build:
      context: .
      target: release
    image: motion:release
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./app:/app
    devices:
      - /dev/video0:/dev/video0
    restart: unless-stopped